# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19WY-PyqtKyEZSsH0Mgg3qn6qvqzujoBn
"""

import streamlit as st
import pandas as pd
import pickle

# Load the saved model and encoders
@st.cache_resource
def load_components():
    with open('rf_model.pkl', 'rb') as file:
        model = pickle.load(file)
    with open('label_encoders.pkl', 'rb') as file:
        encoders = pickle.load(file)
    return model, encoders

model, encoders = load_components()

st.title("✈️ Customer Churn Prediction App")
st.write("""
This app predicts whether a travel customer is likely to **churn** (stop using the services)
based on their profile and behavior. Fill in the details below and click 'Predict'.
""")

col1, col2 = st.columns(2)

with col1:
    age = st.number_input("Age", min_value=18, max_value=100, value=30)
    frequent_flyer = st.selectbox("Frequent Flyer?", ["Yes", "No"])
    annual_income = st.selectbox("Annual Income Class", ["Low Income", "Middle Income", "High Income"])

with col2:
    services_opted = st.slider("Number of Services Opted", min_value=1, max_value=10, value=1)
    social_media = st.selectbox("Account Synced to Social Media?", ["Yes", "No"])
    booked_hotel = st.selectbox("Booked Hotel or Not?", ["Yes", "No"])

if st.button("Predict Churn"):
    input_data = pd.DataFrame({
        'Age': [age],
        'FrequentFlyer': [frequent_flyer],
        'AnnualIncomeClass': [annual_income],
        'ServicesOpted': [services_opted],
        'AccountSyncedToSocialMedia': [social_media],
        'BookedHotelOrNot': [booked_hotel]
    })

    try:
        for col in ['FrequentFlyer', 'AnnualIncomeClass', 'AccountSyncedToSocialMedia', 'BookedHotelOrNot']:
            input_data[col] = encoders[col].transform(input_data[col])

        prediction = model.predict(input_data)[0]
        probability = model.predict_proba(input_data)[0][1]

        st.markdown("---")
        if prediction == 1:
            st.error(f"🚨 **Prediction:** The customer is likely to CHURN. (Probability: {probability:.2%})")
        else:
            st.success(f"✅ **Prediction:** The customer is likely to STAY. (Probability: {(1 - probability):.2%})")

    except Exception as e:
        st.error(f"An error occurred: {e}")